BEGIN
IF NOT EXISTS(SELECT name, collation_name FROM sys.databases WHERE name = DB_NAME() AND collation_name = N'Latin1_General_BIN')
BEGIN
declare @sql varchar(1000)
select @sql = '
ALTER DATABASE ' + DB_NAME() + ' SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
ALTER DATABASE ' + DB_NAME() + ' COLLATE Latin1_General_BIN;
ALTER DATABASE ' + DB_NAME() + ' SET READ_COMMITTED_SNAPSHOT ON;
ALTER DATABASE ' + DB_NAME() + ' SET ALLOW_SNAPSHOT_ISOLATION ON;
ALTER DATABASE ' + DB_NAME() + ' SET MULTI_USER WITH NO_WAIT;
'
EXEC(@sql)
END
END
GO