exec util.dbo.usp_backup_db @dbname = 'ncr_inforce01_IP_IOBOX01', @bu_type = 'full', @comment = 'b4_conversion'

use ncr_inforce01_IP_IOBOX01;
GO

/*
-- NOTE: you must edit the "alter database..." lines below with your database name and then
-- uncomment and run them.
-- These statements allow for SNAPSHOT_ISOLATION which MUST be used to avoid deadlocks
-- between the ION Runtime /embassy applications. And in general MUST be used by
-- application using Hibernate.  See here for details: http://www.hibernate.org/382.html

-- Note you must stop and restart SQLServer after running this commands and
-- you can run the following query to check the results:

--   select name, snapshot_isolation_state, is_read_committed_snapshot_on from sys.databases



-- See here for details: http://www.mssqltips.com/tip.asp?tip=1081

-- WITH ONLINE = ON
-- WITH ALLOW_ROW_LOCKS = OFF
-- WITH ALLOW_PAGE_LOCKS = OFF

*/

-- alter database <DB_NAME> set ALLOW_SNAPSHOT_ISOLATION ON
-- alter database <DB_NAME> set READ_COMMITTED_SNAPSHOT ON

/****** Object:  Table [COR_INBOX_HEADERS]   ******/

ALTER TABLE [COR_INBOX_HEADERS] ALTER COLUMN [C_HEADER_KEY]   [nvarchar](250) NOT NULL;
ALTER TABLE [COR_INBOX_HEADERS] ALTER COLUMN [C_HEADER_VALUE] [nvarchar](250) NOT NULL;
GO

/****** Object:  Table [COR_OUTBOX_HEADERS]   ******/

ALTER TABLE [COR_OUTBOX_HEADERS] ALTER COLUMN [C_HEADER_KEY]   [nvarchar](250) NOT NULL;
ALTER TABLE [COR_OUTBOX_HEADERS] ALTER COLUMN [C_HEADER_VALUE] [nvarchar](250) NOT NULL;
GO

/****** Object:  Table [COR_INBOX_ENTRY]   ******/

DROP INDEX [IX_WAS_PROCESSED_INBOX_TENANT] ON [dbo].[COR_INBOX_ENTRY];
DROP INDEX [IX_CREATED_DATE_TIME_INBOX_TENANT] ON [dbo].[COR_INBOX_ENTRY];
DROP INDEX [IX_WAS_PROCESSED_INBOX_LID] ON [dbo].[COR_INBOX_ENTRY];
DROP INDEX [IX_CREATED_DATE_TIME_INBOX_LID] ON [dbo].[COR_INBOX_ENTRY];
GO

ALTER TABLE [COR_INBOX_ENTRY] ALTER COLUMN [C_TENANT_ID]  [nvarchar](250) NOT NULL;
ALTER TABLE [COR_INBOX_ENTRY] ALTER COLUMN [C_LOGICAL_ID] [nvarchar](250) NULL;
GO

-- The index 'IX_WAS_PROCESSED_INBOX_TENANT' is dependent on column 'C_TENANT_ID'.
-- The index 'IX_CREATED_DATE_TIME_INBOX_TENANT' is dependent on column 'C_TENANT_ID'.
-- ALTER TABLE ALTER COLUMN C_TENANT_ID failed because one or more objects access this column.
-- The index 'IX_WAS_PROCESSED_INBOX_LID' is dependent on column 'C_LOGICAL_ID'.
-- The index 'IX_CREATED_DATE_TIME_INBOX_LID' is dependent on column 'C_LOGICAL_ID'.
-- ALTER TABLE ALTER COLUMN C_LOGICAL_ID failed because one or more objects access this column.

CREATE NONCLUSTERED INDEX [IX_WAS_PROCESSED_INBOX_TENANT] ON [dbo].[COR_INBOX_ENTRY]
(
	[C_WAS_PROCESSED] ASC,
	[C_TENANT_ID] ASC,
	[C_MESSAGE_PRIORITY] DESC,
	[C_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_CREATED_DATE_TIME_INBOX_TENANT] ON [dbo].[COR_INBOX_ENTRY]
(
	[C_WAS_PROCESSED] ASC,
	[C_TENANT_ID] ASC,
	[C_CREATED_DATE_TIME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_WAS_PROCESSED_INBOX_LID] ON [dbo].[COR_INBOX_ENTRY]
(
	[C_WAS_PROCESSED] ASC,
	[C_LOGICAL_ID] ASC,
	[C_MESSAGE_PRIORITY] DESC,
	[C_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_CREATED_DATE_TIME_INBOX_LID] ON [dbo].[COR_INBOX_ENTRY]
(
	[C_WAS_PROCESSED] ASC,
	[C_LOGICAL_ID] ASC,
	[C_CREATED_DATE_TIME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** Object:  Table [COR_OUTBOX_ENTRY]   ******/

DROP INDEX [IX_WAS_PROCESSED_OUTBOX_TENANT] ON [dbo].[COR_OUTBOX_ENTRY];
DROP INDEX [IX_CREATED_DATE_TIME_OUTBOX_TENANT] ON [dbo].[COR_OUTBOX_ENTRY];
DROP INDEX [IX_WAS_PROCESSED_OUTBOX_LID] ON [dbo].[COR_OUTBOX_ENTRY];
DROP INDEX [IX_CREATED_DATE_TIME_OUTBOX_LID] ON [dbo].[COR_OUTBOX_ENTRY];
GO

ALTER TABLE [COR_OUTBOX_ENTRY] ALTER COLUMN [C_TENANT_ID] [nvarchar](250) NOT NULL;
ALTER TABLE [COR_OUTBOX_ENTRY] ALTER COLUMN [C_LOGICAL_ID] [nvarchar](250) NULL;
GO

-- The index 'IX_WAS_PROCESSED_OUTBOX_TENANT' is dependent on column 'C_TENANT_ID'.
-- The index 'IX_CREATED_DATE_TIME_OUTBOX_TENANT' is dependent on column 'C_TENANT_ID'.
-- ALTER TABLE ALTER COLUMN C_TENANT_ID failed because one or more objects access this column.
-- The index 'IX_WAS_PROCESSED_OUTBOX_LID' is dependent on column 'C_LOGICAL_ID'.
-- The index 'IX_CREATED_DATE_TIME_OUTBOX_LID' is dependent on column 'C_LOGICAL_ID'.
-- ALTER TABLE ALTER COLUMN C_LOGICAL_ID failed because one or more objects access this column.

CREATE NONCLUSTERED INDEX [IX_CREATED_DATE_TIME_OUTBOX_LID] ON [dbo].[COR_OUTBOX_ENTRY]
(
	[C_WAS_PROCESSED] ASC,
	[C_LOGICAL_ID] ASC,
	[C_CREATED_DATE_TIME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_CREATED_DATE_TIME_OUTBOX_TENANT] ON [dbo].[COR_OUTBOX_ENTRY]
(
	[C_WAS_PROCESSED] ASC,
	[C_TENANT_ID] ASC,
	[C_CREATED_DATE_TIME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_WAS_PROCESSED_OUTBOX_LID] ON [dbo].[COR_OUTBOX_ENTRY]
(
	[C_WAS_PROCESSED] ASC,
	[C_LOGICAL_ID] ASC,
	[C_MESSAGE_PRIORITY] DESC,
	[C_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_WAS_PROCESSED_OUTBOX_TENANT] ON [dbo].[COR_OUTBOX_ENTRY]
(
	[C_WAS_PROCESSED] ASC,
	[C_TENANT_ID] ASC,
	[C_MESSAGE_PRIORITY] DESC,
	[C_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** Object:  Table [COR_PROPERTY]   ******/

ALTER TABLE [COR_PROPERTY] ALTER COLUMN [C_PROPERTY_NAME] [nvarchar](250) NOT NULL;
ALTER TABLE [COR_PROPERTY] ALTER COLUMN [C_PROPERTY_VALUE] [nvarchar](250) NOT NULL;
GO

/***********************************************/
/***********************************************/
/***********************************************/
  
exec util.dbo.usp_backup_db @dbname = 'ncr_inforce01_IP_IOBOX01', @bu_type = 'full', @comment = 'after_conversion'